spring.application.name=fashonshop
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=${JWT_SECRET:replace-this-with-a-long-secret-key-at-least-32-chars}
app.jwt.expiration-seconds=${JWT_EXPIRATION_SECONDS:259200}